#!/usr/bin/env bash

# Red
LAN="192.168.1"
NETMASK="24"
GATEWAY="192.168.1.254"

# IPs fijas
HAOS_IP="$LAN.6"
CLOUDFLARED_IP="$LAN.7"
ADGUARD_IP="$LAN.8"
FRIGATE_IP="$LAN.9"

# IPs test
ADGUARD_IP_TEST="$LAN.19"

# Una vez instalado AdGuard, todos usarán este DNS
LOCAL_DNS="$ADGUARD_IP"

# Bridge de Proxmox
BRIDGE="vmbr0"

# Zona horaria
TIMEZONE="America/Santiago"

# País
COUNTRY="CL"
