source "$(dirname "$0")/../infra.conf"

NAME="Adguard"
SCRIPT_URL="https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/adguard.sh"

CTID=102
HOSTNAME="adguard"

IP="$CLOUDFLARED_IP/$NETMASK"
DNS="$LOCAL_DNS"