source "$(dirname "$0")/../infra.conf"

NAME="Cloudflared"
SCRIPT_URL="https://community-scripts.org/scripts/cloudflared.sh"

CTID=101
HOSTNAME="cloudflared"

IP="$CLOUDFLARED_IP/$NETMASK"
DNS="$LOCAL_DNS"