source "$(dirname "$0")/../infra.conf"

NAME="Cloudflared"
SCRIPT_URL="https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/cloudflared.sh"

CTID=101
HOSTNAME="cloudflared"

IP="$CLOUDFLARED_IP/$NETMASK"
DNS="$LOCAL_DNS"