source "$(dirname "$0")/../infra.conf"

NAME="Home Assistant"
SCRIPT_URL="https://community-scripts.org/vm/haos.sh"

VMID=100
HOSTNAME="haos"

DISK_SIZE=64
RAM_SIZE=4096
CORE_COUNT=4

IP="$HAOS_IP/$NETMASK"
DNS="$LOCAL_DNS"