#!/usr/bin/env bash
set -e

# Script de automatización de sensores para Proxmox
# Chip ITE IT8613E / IT8628
# Autor: Camilo

KERNEL=$(uname -r)


echo "=============================================="
echo " Verificación Secure Boot"
echo "=============================================="


if [ -d /sys/firmware/efi ]; then

    SECURE_BOOT_FILE=$(find /sys/firmware/efi/efivars/ -name "SecureBoot-*")

    if [[ -n "$SECURE_BOOT_FILE" ]]; then
    
        SECURE_BOOT=$(od -An -t u1 "$SECURE_BOOT_FILE" | awk '{print $NF}')
    
        if [[ "$SECURE_BOOT" == "1" ]]; then
            echo "ERROR: Secure Boot está ACTIVADO"
            exit 1
        fi
    
    fi

fi

echo "Secure Boot desactivado. Continuando."


echo "--- Verificando kernel activo ---"

INSTALLED_KERNEL=$(ls /lib/modules | sort -V | tail -1)


if [[ "$KERNEL" != "$INSTALLED_KERNEL" ]]; then

    echo
    echo "Existe un kernel nuevo instalado."
    echo
    echo "Activo:"
    echo "$KERNEL"
    echo
    echo "Disponible:"
    echo "$INSTALLED_KERNEL"
    echo
    echo "Reinicie antes de continuar."
    exit 1

fi


echo "--- Instalando dependencias ---"

apt update

apt install -y \
    build-essential \
    dkms \
    fancontrol \
    lm-sensors \
    git \
    "pve-headers-$KERNEL"



echo "--- Configurando GRUB ---"

if ! grep -q "acpi_enforce_resources=lax" /etc/default/grub; then

sed -i \
's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="acpi_enforce_resources=lax /' \
/etc/default/grub

update-grub

fi



echo "--- Instalando IT87 DKMS ---"


cd /tmp

rm -rf it87

git clone https://github.com/frankcrawford/it87.git

cd it87


dkms remove it87 --all 2>/dev/null || true


make dkms

echo
echo "--- Verificando DKMS ---"

dkms status

if ! dkms status | grep -q it87; then
    echo "ERROR: IT87 no quedó instalado en DKMS"
    exit 1
fi

depmod -a

echo "--- Configurando carga automática ---"


cat > /etc/modules-load.d/it87.conf <<EOF
it87
EOF


cat > /etc/modprobe.d/it87.conf <<EOF
options it87 force_id=0x8628
EOF

echo "--- Creando configuración fancontrol ---"


if [ -f /etc/fancontrol ]; then
    cp /etc/fancontrol /etc/fancontrol.backup.$(date +%Y%m%d-%H%M)
fi

IT87_PATH=$(readlink -f /sys/class/hwmon/*/name | grep -B1 it8628 | head -1)
CORE_PATH=$(readlink -f /sys/class/hwmon/*/name | grep -B1 coretemp | head -1)

if [[ -z "$IT87_PATH" || -z "$CORE_PATH" ]]; then
    echo "ERROR: No se encontraron sensores IT8628/coretemp."
    echo "Ejecute sensors y revise."
    exit 1
fi

cat > /etc/fancontrol <<EOF
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=10
DEVPATH=hwmon1=devices/platform/it87.2608 hwmon2=devices/platform/coretemp.0
DEVNAME=hwmon1=it8628 hwmon2=coretemp
FCTEMPS=hwmon1/pwm3=hwmon2/temp1_input hwmon1/pwm2=hwmon2/temp1_input hwmon1/pwm1=hwmon2/temp1_input
FCFANS=hwmon1/pwm3= hwmon1/pwm2= hwmon1/pwm1=
MINTEMP=hwmon1/pwm3=40 hwmon1/pwm2=40 hwmon1/pwm1=40
MAXTEMP=hwmon1/pwm3=70 hwmon1/pwm2=70 hwmon1/pwm1=70
MINSTART=hwmon1/pwm3=100 hwmon1/pwm2=100 hwmon1/pwm1=100
MINSTOP=hwmon1/pwm3=50 hwmon1/pwm2=50 hwmon1/pwm1=50
EOF



echo "--- Activando fancontrol ---"


systemctl enable fancontrol || true

if systemctl restart fancontrol; then
    echo "fancontrol iniciado correctamente"
else
    echo "ADVERTENCIA: fancontrol no pudo iniciar"
    echo "Ejecute: systemctl status fancontrol"
fi


echo
echo "=============================================="
echo " Instalación completada"
echo "=============================================="

echo
echo "Reinicie el servidor:"
echo
echo " reboot"
echo
echo "Después:"
echo
echo " sensors"
echo " systemctl status fancontrol"
echo
